
default: &default
  adapter: mysql2
  encoding: utf8
  # host: 159.223.99.133
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  # port: 3306
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: Rocket_Elevators_Information_System_development


test:
  <<: *default
  database: Rocket_Elevators_Information_System_test


production:
  <<: *default
  database: Rocket_Elevators_Information_System_production
  username: Rocket_Elevators
  password: <%= ENV['qetuo2468'] %>
