
default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: lemath
  password: kintaro1
  

development:
  <<: *default
  database: Rocket_Elevators_Information_System_development
  adapter: mysql2
  socket: /var/run/mysqld/mysqld.sock
<<<<<<< HEAD
  username: root  
  password: root1234
=======
>>>>>>> d72f8571279364fec92dc5f49c96a7a25b82a414

test:
  <<: *default
  database: Rocket_Elevators_Information_System_test
  adapter: mysql2
  socket: /var/run/mysqld/mysqld.sock


production:
  <<: *default
  database: Rocket_Elevators_Information_System_production
  username: Rocket_Elevators
  password: <%= ENV['qetuo2468'] %>
  adapter: mysql2
  socket: /var/run/mysqld/mysqld.sock

secondbase:
  development:
    <<: *default
    database: postgres_db_development
    adapter: postgresql

  test:
    <<: *default
    database: postgres_db_test
    adapter: postgresql

  production:
    <<: *default
    url: <%= ENV['POSTGRES_DB_DATABASE_URL'] %>
    adapter: postgresql
    username: codeboxx
    password: Codeboxx1!